### ISSUE TITLE
Have you considered about adding a calculation for conv1d?

### ISSUE THREAD

**Issue by viviov** [Lyken17/pytorch-OpCounter#10]
like the title

**Comment by Lyken17** [comment]
will do.

**Comment by Lyken17** [comment]
Thanks @Tom2718 , hook for conv1 has been added. https://github.com/Lyken17/pytorch-OpCounter/pull/11

**Comment by Lyken17** [comment]
Done, I have implemented a more general ConvNd profiler https://github.com/Lyken17/pytorch-OpCounter/blob/master/thop/count_hooks.py#L9 Have a check.
