### ISSUE TITLE
The problem of count_parameters() in basic_hooks.py

### ISSUE THREAD

**Issue by YunanZhu** [Lyken17/pytorch-OpCounter#112]
I saw #75 and the corresponding [commit 495f6d7](https://github.com/Lyken17/pytorch-OpCounter/commit/495f6d781875e8e2ba22102d2149bcddf9818937).

If you put `m.register_forward_hook(count_parameters)` right behind `m.register_forward_hook(fn)`:
```python
handler_collection[m] = (m.register_forward_hook(fn), m.register_forward_hook(count_parameters))
```
And def `count_parameters` as:
```python
def count_parameters(m, x, y):
    total_params = 0
    for p in m.parameters():
        total_params += torch.DoubleTensor([p.numel()])
    m.total_params[0] = total_params
```

It seems that `count_parameters` will eliminate the result of `fn`. It just means that whatever you do to `total_params` in `fn`, the `total_params` will always be reset by `count_parameters`.

<br>

An example:
```python
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.model = nn.Conv2d(3, 3, kernel_size=3, stride=1, padding=0)

    def forward(self, x):
        return self.model(x)


net = Net()

ipt = torch.randn(size=[1, 3, 3, 3])

macs, params = profile(net, (ipt,), verbose=False)
print(macs, params)  # It will print "84.0 84.0".


def count_net(m, x, y):
    m.total_ops += torch.tensor(data=12315, dtype=torch.float64)
    m.total_params += torch.tensor(data=70000, dtype=torch.float64)


macs, params = profile(net, (ipt,), custom_ops={Net: count_net}, verbose=False)
print(macs, params)  # It will print "12315.0 84.0".
```

<br>

Then, if I swap the order of these 2 hooks:
```python
handler_collection[m] = (m.register_forward_hook(count_parameters), m.register_forward_hook(fn))
```
Or modify the code in `count_parameters`:
```python
def count_parameters(m, x, y):
    total_params = 0
    for p in m.parameters():
        total_params += torch.DoubleTensor([p.numel()])
    m.total_params += total_params  # m.total_params[0] = total_params
```
It will print `12315.0 70084.0` at the 2nd time.

<br><br>

At the end, I have another little problem in `count_parameters` in /thop/vision/basic_hooks.py,
If `m.total_params` is a tensor with shape=1, and `total_params` is a tensor with shape=1 too.
Why `m.total_params[0] = total_params` can work?

**Comment by chenghaoDong666** [comment]
As for why `m.total_params[0]=total_params`can work, if `m.parameters()`is None, then total_params=0,whose type is int.   If it is `m.total_params=total_params`,then it will except a TypeError: cannot assign 'int' as buffer 'total_params' (torch.Tensor or None expected)

**Comment by Lyken17** [comment]
Yes, this is indeed an bug and thanks for @chenghaoDong666 I have fixed in https://github.com/Lyken17/pytorch-OpCounter/blob/f0a57ab5643643a1b4f206065b66d73df750397d/thop/profile.py#L201
