### ISSUE TITLE
Maybe a bug.

### ISSUE THREAD

**Issue by Daibingh** [Lyken17/pytorch-OpCounter#114]
https://github.com/Lyken17/pytorch-OpCounter/blob/d1920d3400a62678ab3c2cf21ba13db35921713c/thop/profile.py#L194

in function dfs_count(), near line 194, I think it shoud be 
```py
total_ops, total_params = module.total_ops.item(), 0
```
otherwise I get a wrong result.

Maybe I am wrong. 
Thanks.

**Comment by Lyken17** [comment]
Yes, this is indeed an bug and thanks for @chenghaoDong666 I have fixed in https://github.com/Lyken17/pytorch-OpCounter/blob/f0a57ab5643643a1b4f206065b66d73df750397d/thop/profile.py#L201
