### ISSUE TITLE
About the Params(M) FLOPs(G) displayed in your result

### ISSUE THREAD

**Issue by dujiangsu** [Lyken17/pytorch-OpCounter#12]
Hi,

The tool you developed is very helpful.

But I am a little confused about the unit used in your result. 

For example, here Params(M) should be the number of parameters, not the size?
![image](https://user-images.githubusercontent.com/12018307/54488702-05482880-48e0-11e9-97c8-94a78b7a1623.png)

 And how about FLOPs(G), 1x10^9 flops the total forward and backward for a model? But the result you got is quite different from the tensorflow profiler's result. So, I am a little confused.

**Comment by Lyken17** [comment]
| Params(M) should be the number of parameters, not the size?

Yes, Params(M) is the number of total paramteres. 

| But the result you got is quite different from the tensorflow profiler's result

For VGG model, it is because the different constant value of `multiply_adds`.

**Comment by Lyken17** [comment]
In addition, when talking FLOPs, people care more about the deployment. Thus here `THOP` only considers forward.

**Comment by dujiangsu** [comment]
Thanks!
