### ISSUE TITLE
Not implemented for  Conv3d

### ISSUE THREAD

**Issue by ys-dpc** [Lyken17/pytorch-OpCounter#13]
First of all, thanks to the author's selfless dedication, your code is well written! 
  
  Now 3D convolution is widely used. Have you considered supporting 3D convolution?

**Comment by Lyken17** [comment]
Done, I have implemented a more general ConvNd profiler https://github.com/Lyken17/pytorch-OpCounter/blob/master/thop/count_hooks.py#L9 Have a check.

**Comment by slighting666** [comment]
@ys-dpc 
hi ！
How to calculate 3D CNN flops？ thanks
