### ISSUE TITLE
Model cannot feedforward after profile if it contains shared modules passed through a function

### ISSUE THREAD

**Issue by xuefei1** [Lyken17/pytorch-OpCounter#142]
The following code would crash on the last line:
```
    def get_model(act):
        return torch.nn.Sequential(
                    torch.nn.Conv2d(16, 16, (3, 3), (1, 1), (1, 1)),
                    act
        )
    shared_act = torch.nn.ReLU()
    conv2d = torch.nn.Sequential(
        get_model(shared_act),
        get_model(shared_act),
    )
    _macs, _n_params = profile(conv2d,
                               inputs=(torch.ones(1, 16, 480, 480),),
                               verbose=True)
    print("Conv2D FLOPS 480x480: {:.5f}M".format(_macs * 2 / 1e6))
    out = conv2d(torch.ones(1, 16, 480, 480)) # AttributeError: 'ReLU' object has no attribute 'total_ops'
```
I think it is because somehow the forward hook is not removed on the shared module but the total_ops attribute is removed, but I'm not sure.

**Comment by Lyken17** [comment]
Thanks for pointing it out. Yes, this is a bug (?) since THOP currently does not support re-used modules. I will patch and fix it.

**Comment by lvmingzhe** [comment]
Similar problems here.

**Comment by KirinAllen** [comment]
Similar problems here: AttributeError: 'Conv2d' object has no attribute 'total_ops'

**Comment by lvmingzhe** [comment]
> Similar problems here: AttributeError: 'Conv2d' object has no attribute 'total_ops'

I think #99  would solve your problem.
