### ISSUE TITLE
Is the count_conv2d for FLOPs?

### ISSUE THREAD

**Issue by sungsooo** [Lyken17/pytorch-OpCounter#15]
I think the count_conv2d function is for MACC or Multiplications.
In this function, total_ops is calculated by K x K x Cin x Wout x Hout X Cout.
Isn't it for the MACC calculation?

**Comment by Lyken17** [comment]
Umm, I don't get what you mean. Can you explain more detailly?

**Comment by sungsooo** [comment]
I understand that one multiplication or one addition can be seen as one FLOP.
I wonder what is mean the multiply-add = 1 in your code.

And can you know me how can I calculate MACs ?

**Comment by Lyken17** [comment]
In some cases, a multiplication is treated as 2 additions. So I put a `multiply_adds` constant to ease the modification. 

MACs = 2 * FLOPs, you may convert it by yourself.  https://en.wikipedia.org/wiki/Multiply%E2%80%93accumulate_operation

**Comment by sungsooo** [comment]
Generally, MACs consider multiplication and addition as one operation, as far as I know. Are the FLOPs two operation in that case?

**Comment by Lyken17** [comment]
I think so.

**Comment by sungsooo** [comment]
In this equation MACs = 2 * FLOPs, If I want to get MACs, do I have to multiply FLOPs by 2?
MACs can be bigger than FLOPs according to the equation. But I think the MACs should be smaller than FLOPs.

**Comment by sungsooo** [comment]
Do you plan to make bilinear interpolate layer?
