### ISSUE TITLE
Should I skip things like 'Sequential', 'Bottleneck' when calculating FLOPs ? (just treat it as zero)

### ISSUE THREAD

**Issue by StonepageVan** [Lyken17/pytorch-OpCounter#155]
Hello my friend, you have done a very great work, appreciate! Now I ve got a model which need to be calculating FLOPs, it has outter function just like Sequential and Bottleneck (contain conv2d bn etc.). Could you please tell me if thop method have calculated the inner conv, shall we need to calculated the outter corresponding function's(Sequential and Bottleneck) FLOPs again?

**Comment by Lyken17** [comment]
You do not need to manually calculate this. THOP will treat these modules as zero flops and sum up children modules' flops.

**Comment by StonepageVan** [comment]
THANK YOU VERY MUCH! this helps a lot~
