### ISSUE TITLE
pip install failed, and 'torch.Size' object has no attribute 'nume

### ISSUE THREAD

**Issue by luzhilin19951120** [Lyken17/pytorch-OpCounter#16]
When I used pip install thop, I got
> Could not find a version that satisfies the requirement thop (from versions: )

When I installed thop from source and used it to resnet50 model, I got the following error message:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-97c8f2a14ac8> in <module>()
----> 1 flops, params = profile(model, input_size=(1, 3, 224,224))

<ipython-input-9-f29adc437490> in profile(model, input_size, custom_ops, device)
     73     x = torch.zeros(input_size).to(device)
     74     with torch.no_grad():
---> 75         model(x)
     76 
     77     total_ops = 0

/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchvision/models/resnet.py in forward(self, x)
    137 
    138     def forward(self, x):
--> 139         x = self.conv1(x)
    140         x = self.bn1(x)
    141         x = self.relu(x)

/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
--> 479             hook_result = hook(self, input, result)
    480             if hook_result is not None:
    481                 raise RuntimeError(

<ipython-input-7-4b52514e62d1> in count_convNd(m, x, y)
     10     batch_size = x.size(0)
     11 
---> 12     kernel_ops = m.weight.size()[2:].numel()
     13     bias_ops = 1 if m.bias is not None else 0
     14     ops_per_element = kernel_ops + bias_ops

AttributeError: 'torch.Size' object has no attribute 'numel'

**Comment by Jiangchitang** [comment]
I also encountered this problem. Did you solve it?

**Comment by Lyken17** [comment]
The `numel` function for `torch.Size` is introduced in torch 1.0. Please upgrade your pytorch.

**Comment by Jiangchitang** [comment]
@Lyken17 Excellent！

**Comment by im-wll** [comment]
> The `numel` function for `torch.Size` is introduced in torch 1.0. Please upgrade your pytorch.

if I don't want to upgrade pytorch,how can I modify the code?
