### ISSUE TITLE
Is matmul operation automatically considered?

### ISSUE THREAD

**Issue by GostInShell** [Lyken17/pytorch-OpCounter#167]
Is a `torch.matmul` operation implemented in a `forward` layer automatically considered?

**Comment by GostInShell** [comment]
The `matmul` implemented here
https://github.com/Lyken17/pytorch-OpCounter/blob/509fb7e7e48faaddd4b436371ccd39ede77f1f4a/thop/vision/counter.py#L67
seems to be used in 
https://github.com/Lyken17/pytorch-OpCounter/blob/d74140c41dc194a557270b9de2f9811fbb537816/thop/vision/onnx_counter.py#L19
Does this indicate the FLOPs of `matmul` will be considered when using ONNX model rather than a pytorch one?

**Comment by timmywanttolearn** [comment]
Yes it will. 
ONNX model depends on operators, while PyTorch model consists of layers. You will get similar results when using both models(if we have implemented related operators and layers).

**Comment by GostInShell** [comment]
Thanks a lot! That perfectly solved my confusion!
