### ISSUE TITLE
When I calculate the flops of Torch.nn.upsample, I found that Hook in the Forward process will override the output of UpSample. Is this BUG or a special design?

### ISSUE THREAD

**Issue by tty0013** [Lyken17/pytorch-OpCounter#169]
When I calculate the flops of torch.nn.upsample, I found that hook function for Upsample in the forward process will override the output of UpSample. Is this BUG or a special design?

my Upsample:
``` python
nn.Upsample(size=None, scale_factor=2, mode='nearest')
```

This is the code that handles forward_hook in the pytorch framework:
``` python
result = forward_call(*input, **kwargs)
if _global_forward_hooks or self._forward_hooks:
    for hook in (*_global_forward_hooks.values(), *self._forward_hooks.values()):
        hook_result = hook(self, input, result)
        if hook_result is not None:
            result = hook_result
```
It can be seen that if hook_function returns a value, the output of the Upsample module will be overwritten.

In the hook function of the UpSample, the return statement is called, returned 0:
``` python
def count_upsample(m, x, y):
    if m.mode not in (
        "nearest",
        "linear",
        "bilinear",
        "bicubic",
    ):  # "trilinear"
        logging.warning("mode %s is not implemented yet, take it a zero op" % m.mode)
        return counter_zero_ops()
    
    # In my case, the following statement is executed
    if m.mode == "nearest":
        return counter_zero_ops()

    x = x[0]
    m.total_ops += counter_upsample(m.mode, y.nelement())

def counter_zero_ops():
    return torch.DoubleTensor([int(0)])
```

version Information:
thops:  0.0.5-2204160952
pytorch: 1.10.2

Therefore, in the current version of thop, calculating the FLOPs of a Upsample module destroys the original output value of the module. Of course, I'm not sure if this is a special setting.

**Comment by tianyuan168326** [comment]
I also meet with this problem, and wast about 1 hour for this problem.
Altought it can be easily fixed in the source code, I hope the author can notice it.

**Comment by Lyken17** [comment]
@tianyuan168326 @tty0013 

Does this issue still exist? Or already fixed in latest version?

**Comment by Lyken17** [comment]
PyTorch hook should not affect any forward results, the x and y are never modified during profiling.

**Comment by tianyuan168326** [comment]
It is fixed in the laster version! @Lyken17
