### ISSUE TITLE
Different result of Resnet50 

### ISSUE THREAD

**Issue by USTClj** [Lyken17/pytorch-OpCounter#17]
Hi, thank you so much for your awesome work! I run the following code:
`from torchvision.models import resnet50
from thop import profile
model = resnet50()
flops, params = profile(model, input_size=(1, 3, 224,224))
print(flops, params)`

But I get the output: 
**4142713856.0 25557032.0** , 
which is different from your results in the table of README. And I'am using pytorch 1.0.1.
Could you help me explain that? Thank you!

**Comment by SWHL** [comment]
I have the same result with @USTClj  after running the following code:
```python
from torchvision.models import resnet50 
from thop import profile 
model = resnet50() 
flops, params = profile(model, input_size=(1, 3, 224,224)) print(flops, params)
```
Result:
```text
flops: 4142627840.0
params: 25557032.0
```
Environment:
```text
PyTorch: 1.0.0
```

**Comment by ChristineRYY** [comment]
@Lyken17 I get the same result. But I don't know what the units of flops and params are. And how to convert them to M and G?

**Comment by Lyken17** [comment]
@ChristineRYY 
M = 1024 ^ 2
G = 1024 ^ 3

**Comment by zpkosmos** [comment]
@Lyken17 
It seems that 4142713856.0=3.858G
However，in your README，it is 3.53G what is the problem？

**Comment by Lyken17** [comment]
@zpkosmos There are some bugs in my previous counting implementations. I have updated the readme to match the latest version. Please check it out.

Besides, you can generate the table using

```python
import torch
from torchvision import models
from thop.profile import profile

model_names = sorted(name for name in models.__dict__ if
                     name.islower() and not name.startswith("__") and not "inception" in name
                     and callable(models.__dict__[name]))

print("%s | %s | %s" % ("Model", "Params(M)", "FLOPs(G)"))
print("---|---|---")

device = "cpu"
if torch.cuda.is_available():
    device = "cuda"
for name in model_names:
    model = models.__dict__[name]().to(device)
    inputs = torch.randn((1, 3, 224, 224)).to(device)
    total_ops, total_params = profile(model, (inputs, ), verbose=False)
    print("%s | %.2f | %.2f" % (name, total_params / (1024 ** 2), total_ops / (1024 ** 3)))

```
