### ISSUE TITLE
Does it think about to support torch.nn.PixelShuffle? It is widely used in Super-Resolution.

### ISSUE THREAD

**Issue by wangqiim** [Lyken17/pytorch-OpCounter#178]
https://pytorch.org/docs/stable/generated/torch.nn.PixelShuffle.html

**Comment by wangqiim** [comment]
It looks like it's always going to be 0 Flops :joy:

**Comment by Lyken17** [comment]
I think it is already added? PixelShuffle operation does not contain any multiplications, thus should be zero macs.

**Comment by wangqiim** [comment]
I don't think it is added. I just open a pull request.

**Comment by Lyken17** [comment]
PR Merged. Thanks for the contribution!
