### ISSUE TITLE
code is wrong

### ISSUE THREAD

**Issue by yxlijun** [Lyken17/pytorch-OpCounter#18]
kernel = torch.Tensor([*(x[0].shape[2:])]) // torch.Tensor(list((m.output_size,))).squeeze()
                           ^
SyntaxError: invalid syntax

**Comment by Lyken17** [comment]
Make sure you are running the lastest version of pytorch.

**Comment by Lyken17** [comment]
Close due to inactivity. Feel free to reopen it if the issue still occurs.

**Comment by hugddygff** [comment]
@Lyken17 I also met this problem, can you check it again??

**Comment by hugddygff** [comment]
@yxlijun did you solve this problem?

**Comment by Lyken17** [comment]
Without line number and detailed information to reproduce, I am afraid there is nothing I can do to help.

**Comment by zhouyuan888888** [comment]
> @yxlijun did you solve this problem?

Hi，elimate “*” in this line will fix this bug
