### ISSUE TITLE
Does this library work with einops?

### ISSUE THREAD

**Issue by vedantroy** [Lyken17/pytorch-OpCounter#183]
If I use the einops package (https://github.com/arogozhnikov/einops), will this library still be able to accurately the # of flops in my model?

**Comment by Lyken17** [comment]
I am afraid not. Einops is not a Module-level operation and currently it is not traced by thop.

I am working on some alternatives using onnx or torch.fx to trace such a behavior.

**Comment by vedantroy** [comment]
Got it. Thanks for the response!
