### ISSUE TITLE
A typo in evaluate_famous_models.py

### ISSUE THREAD

**Issue by lvmingzhe** [Lyken17/pytorch-OpCounter#186]
Line 13 : print("%s | %s | %s" % ("Model", "Params(M)", "FLOPs(G)"))

I doubt that "FLOPs(G)" here should be "MACs(G)".

**Comment by Lyken17** [comment]
Thanks for the reminder. Could you scratch a PR to help fix? I am travelling and might be unable to code,

**Comment by lvmingzhe** [comment]
Roger that.
I will do it.
