### ISSUE TITLE
[feature] Can it support only calculate the parameters which `requires_grad == True`?

### ISSUE THREAD

**Issue by Freed-Wu** [Lyken17/pytorch-OpCounter#190]
Thanks.

**Comment by SysuJayce** [comment]
I have the same problem when setting weight in `__init__()` with `nn.Parameter()` manually and call `nn.functional.conv` in `forward()`

**Comment by Freed-Wu** [comment]
I suggest <https://github.com/TylerYep/torchinfo> which support displaying:

```text
Total params: 11,689,512
Trainable params: 11,689,512
Non-trainable params: 0
Total mult-adds (G): 2.37
```
