### ISSUE TITLE
skip connection structure

### ISSUE THREAD

**Issue by ZhenpengChenCode** [Lyken17/pytorch-OpCounter#2]
It seems that the OpCounter doesn't take into account the skip connection structure.

**Comment by ZhenpengChenCode** [comment]
Resnet flops calculated by the OpCOunter is smaller than the value in paper.

**Comment by Lyken17** [comment]
Yes, as pytorch is a dynamic graph library, it is impossible to determine skip-connection structure at nn.Module level. 

One quick fix is to write a special judge for inverted residual block. I'll try to provide a more precise  one via tracing computational graph.

**Comment by Kylin9511** [comment]
@Lyken17 In torch1.1, a new placeholder  module is provided for this kind of awkward situation.

See [`torch.nn.Idnetity`](https://pytorch.org/docs/stable/nn.html?highlight=identity#torch.nn.Identity)

As I can see, you should add this Module into `count_hooks.py` and `profile.py`, counting the extra ops for skip connection. 

__And update your readme for special notice is important as well.__

**Comment by Lyken17** [comment]
not really. Most existing codebase still defines the identity connection in `forward`. The real problem, as I mentioned before, is pytorch's `define-by-run` philosophy. The only way to record all operations is to trace the DAG. 

In this case, please have a look at my labmate's project [onnx-profiler](https://github.com/zhijian-liu/onnx-profiler)

**Comment by Kylin9511** [comment]
What you mentioned is quite right. I didn't say it would fix this problem without changing the codes. If someone would like to call your hook based op-counter while considering skip connection, he can represent skip connection with `nn.Identity`. And by adding this module to your `profile` we can fix the problem.

It is kind of a patch, not a global solution.

By unify the model to onnx mode is a very interesting idea, I may look deeper into it some time.

**Comment by Kylin9511** [comment]
It is kind of like a user-defined patch, so I don't think you should update your project.
