### ISSUE TITLE
Count hook for convtranspose2d  is wrong

### ISSUE THREAD

**Issue by bl0** [Lyken17/pytorch-OpCounter#20]
Hi, thanks for your great work. I found an error in the following codes:
https://github.com/Lyken17/pytorch-OpCounter/blob/41d9d15e427b142af0d85fff5344f6e49dce542d/thop/count_hooks.py#L66-L71
It calculates `ops_per_element` with two different methods. The first is kh * kw * cin, while the second is  kh * kw * cin * cout. Obviously, the first one is right, but it's overwrited by the second one.

**Comment by feiyangha** [comment]
Hi, I agree with you. The flops of convtranspose2d using this method is too huge.

**Comment by Lyken17** [comment]
Thanks for pointing out. I've fixed. Let me know if you find other errors in count hook.
