### ISSUE TITLE
How to convert from number of params to memory usage?

### ISSUE THREAD

**Issue by Tramac** [Lyken17/pytorch-OpCounter#23]
Hi, thank you for your work! The output is number of params, how to convert it to memory usage just like in `README`?

**Comment by Lyken17** [comment]
I usually use `nvidia-smi`. Let me know if you have other methods.

**Comment by Lyken17** [comment]
The number of parameters does not reflect to the actual memory usage. For example, for a same `conv2d`, the memory footprint can vary a lot for different input resolutions.
