### ISSUE TITLE
cannot run the program under pytorch 1.1

### ISSUE THREAD

**Issue by ujsyehao** [Lyken17/pytorch-OpCounter#24]
It has multiple errors:

- profile.py", line 70, in profile
    original_device = model.parameters().__next__().device
AttributeError: 'generator' object has no attribute '__next__'

**Comment by Lyken17** [comment]
Are you running the latest code ？In lastest code, it should be 

```python
    original_device = model.parameters().__next__().device
```

https://github.com/Lyken17/pytorch-OpCounter/blob/master/thop/profile.py#L70

Can you try `pip install --upgrade git+https://github.com/Lyken17/pytorch-OpCounter.git` to update?

**Comment by Lyken17** [comment]
Close due to inactivity. Feel free to re-open it if necessary.
