### ISSUE TITLE
python2 syntax error

### ISSUE THREAD

**Issue by yabinzhangJohn** [Lyken17/pytorch-OpCounter#25]
It seems that thop only support python3. 
In python2.7, there will be syntax error.
```
thop-0.0.22-py2.7.egg/thop/count_hooks.py, line 119
kernel = torch.Tensor([*(x[0].shape[2:])]) // torch.Tensor(list((m.output_size,))).squeeze()
SyntaxError: invalid syntax
```

**Comment by Lyken17** [comment]
Python 2 is going to deprecated in 2019. There is no plan to support it.

**Comment by Lyken17** [comment]
Between, it seems you are installing through PyPi. The continuous integration build on CI is not working currently. Use Github to install the latest version

```pip install --upgrade git+https://github.com/Lyken17/pytorch-OpCounter.git```
