### ISSUE TITLE
Hi, How to make our own rules

### ISSUE THREAD

**Issue by huyalvchuan** [Lyken17/pytorch-OpCounter#27]
Thanks!

**Comment by Lyken17** [comment]
You may want to look at [thop/count_hooks.py](https://github.com/Lyken17/pytorch-OpCounter/blob/master/thop/count_hooks.py#L9). After defining your own rule, you can register it in hooks

```python
flops, params = profile(model, inputs=(input, ), 
                        custom_ops={YourModule: count_your_model})
```
