### ISSUE TITLE
About the maxpooling

### ISSUE THREAD

**Issue by Kylin9511** [Lyken17/pytorch-OpCounter#29]
May I ask why do you disable all the maxpooling part of your codes?

https://github.com/Lyken17/pytorch-OpCounter/blob/1f4ddb7fb51c3b1a49d60708f9b857535e5dc4e1/thop/profile.py#L23-L28

https://github.com/Lyken17/pytorch-OpCounter/blob/1f4ddb7fb51c3b1a49d60708f9b857535e5dc4e1/thop/count_hooks.py#L111-L125

**Comment by Lyken17** [comment]
MAX operation does not involve any addition nor multiplication, thus should be calculated.

**Comment by Kylin9511** [comment]
@Lyken17 I see, it seems to be an stupid question~ Awkward😅

**Comment by rrryan2016** [comment]
> multiplication

Hello, I find you update maxpooling FLOPs calculation in the latest version, as  https://github.com/Lyken17/pytorch-OpCounter/blob/41d9d15e427b142af0d85fff5344f6e49dce542d/thop/count_hooks.py#L110-L115
