### ISSUE TITLE
Restriction on reused modules might be too strict

### ISSUE THREAD

**Issue by Kylin9511** [Lyken17/pytorch-OpCounter#30]
It seems that the reuse of module is banned by THOP tools

https://github.com/Lyken17/pytorch-OpCounter/blob/1f4ddb7fb51c3b1a49d60708f9b857535e5dc4e1/thop/profile.py#L49-L51

However, it is not quite reasonable. The re-use of ReLU-type module is very common, it can make your codes neater and causes no harm. e.g.
``` python
class Model(nn.Module):
  def __init__(self):
    super().__init__()
    self.dropout = nn.Dropout(0.5)
    self.relu = nn.ReLU()
    self.lin1 = nn.Linear(4096, 4096)
    self.lin2 = nn.Linear(4096, 4096)
    self.lin3 = nn.Linear(4096, 4096)
  def forward(self, x):
    output = self.relu(self.lin1(x))
    output = self.relu(self.lin2(output))
    output = self.dropout(self.relu(self.lin3(output)))
    ....
```

Besides, __I think the network legality check is not THOP's work to do.__ This kind of restriction is unnecessary and will cause troublesome Error raise as I can see.

**Comment by Kylin9511** [comment]
And if you truly want to show your attitude toward module re-use that much, [warnings](https://docs.python.org/3/library/warnings.html#module-warnings) is more recommended as it won't interrupt the program. 😄

By raising it you're generating error, rather than real warning.

**Comment by Lyken17** [comment]
Question, does the example code you provide trigger the warning? Since though ReLU is forwarded several times, the registration should only happen once.

**Comment by Kylin9511** [comment]
@Lyken17 Sorry that I didn't dig deep into your code's logic, see the following NN design instead.

``` python
class SomeNet(nn.Module):
    def __init__(self, reduction=4):
        super(SomeNet, self).__init__()
        self.activation = nn.LeakyReLU(negative_slope=0.3, inplace=True)

        self.encoder_feature = nn.Sequential(OrderedDict([
            ("conv3x3_bn", conv3x3_bn(in_channel, 2)),
            ("activation", self.activation),
        ]))
        ...
```

The problem has nothing to do with module reuse in forward function. THOP will recursively enter each leaf `nn.Module` and detect if there exist any "re-defined" module. 

However, the aforementioned re-defined is legal, since I want to define a globally same activation function and plant it in many sub-module. And THOP stop me from doing that.

Like I said, __even my definition of network is wrong, it is not THOP's job to point it out. And even if THOP would like to point it out, warnings rather than Raise Error should be used.__ 

As a flops counting tools, it should not do extra judgement or security check. A correct flops and params output is the only thing to focus on.

**Comment by Lyken17** [comment]
It is a weird usage, I have to say. For your code example, each activation should have its own nn.Module. The proper case should be a recurrent structure where one layer is used in different depth. I have relaxed the check: now it only prints the warning instead of raises it.

**Comment by Kylin9511** [comment]
Yet a legal one and a convinient one, too. Still unable to get your points of checking user's network... If I were you I would cancel the redundant check, but after all it is your project 😂
