### ISSUE TITLE
clever_format is not exposed yet

### ISSUE THREAD

**Issue by Kylin9511** [Lyken17/pytorch-OpCounter#31]
The original output of profile is too ugly and it seems that you add a visualization tool in `utils`

https://github.com/Lyken17/pytorch-OpCounter/blob/1f4ddb7fb51c3b1a49d60708f9b857535e5dc4e1/thop/utils.py#L2-L8

However, the `clever_format` tool is not included in the `__init__` so it can not be smoothly called. My recommendation is add an `clever_format` in your `profile` arguments, and make it `True` by default.

https://github.com/Lyken17/pytorch-OpCounter/blob/1f4ddb7fb51c3b1a49d60708f9b857535e5dc4e1/thop/profile.py#L42-L43

**Comment by Lyken17** [comment]
Good suggestion. You are welcome to submit a pull request.

**Comment by Kylin9511** [comment]
@Lyken17 Well of course, I can make a PR as the conclusion after the current three topics are closed.

**Comment by Lyken17** [comment]
The proposal is now merged. Thanks for @Kylin9511's contribution
