### ISSUE TITLE
Pypi installation failed

### ISSUE THREAD

**Issue by dhkim0225** [Lyken17/pytorch-OpCounter#4]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/16400591/49358056-a980d780-f714-11e8-99ed-c564c6076e01.png">

What's reason of this??

python 2.7.12
python 3.6.7
ubuntu 16.04 64bit

**Comment by Lyken17** [comment]
not sure what happened. Can you check what mirror you are using? 

Between,  installing from git should work for your case.
`pip install --upgrade git+https://github.com/Lyken17/pytorch-OpCounter.git`

**Comment by Lyken17** [comment]
Close due to inactivity.
