### ISSUE TITLE
fix a bug when use pytorch0.4.1.

### ISSUE THREAD

**Issue by yjump** [Lyken17/pytorch-OpCounter#40]
Hi, 
   Thank you for this repo. when I use this repo to count flops and params on pytorch0.4.1. there is an error occur like:
File "~/site-packages/thop/count_hooks.py", line 20, in count_convNd
    kernel_ops = m.weight.size()[2:].numel()  # Kw x Kh
AttributeError: 'torch.Size' object has no attribute 'numel'

   I only use conv2d so I change this line like:
   kernel_ops = m.weight.size()[2]*m.weight.size()[3] 
   
   I think you can offer different pytorch-OpCounter Branch for different pytorch version if there is   someone needs. Or remind others who are in need.

   Anyway, thanks and BRs.

**Comment by Lyken17** [comment]
I do not have the bandwidth to support old versions currently. You are welcome to submit a PR if you would like to help. 

For your case, you can replace `numel` with multiplication which has the same semantic meanings.

**Comment by Lyken17** [comment]
Close to due to the unclear description.
