### ISSUE TITLE
flops for depthwise convolution layer

### ISSUE THREAD

**Issue by pgr2015** [Lyken17/pytorch-OpCounter#41]
Hi, first of all, thank you for your code. It really helps my work.
I am curious about the flops for depthwise convolutional layer, which should be different from the standard conv. 
But it seems there is no implementation for such layer in your code. Could you please add support for it?
Thanks!

**Comment by Lyken17** [comment]
Current counting already considers the case.

https://github.com/Lyken17/pytorch-OpCounter/blob/master/thop/count_hooks.py#L24

**Comment by pgr2015** [comment]
Thank you for your reply! Sorry that I am not familar with pytorch API.

I have checked your code and pytorch documentation, if I understand correctly, the parameter m.groups distinguish the standard conv and depthwise conv. For  standard conv m.groups will be 1, but for depthwise conv m.groups will be the number of output channel.
Hope to get your reply, thanks!

**Comment by ujsyehao** [comment]
@pgr2015  yes
