### ISSUE TITLE
vgg16 calculate result different from the project's table

### ISSUE THREAD

**Issue by ujsyehao** [Lyken17/pytorch-OpCounter#43]
I use thop  to calculate params, flops of vgg16, the code below:
![98](https://user-images.githubusercontent.com/17454232/64095307-0dfac100-cd91-11e9-9984-fa88650dd6b7.jpg)
The result is:
15.607G 138.358M

but in your readme.md, 

vgg16 | 131.95 | 14.54
-- | -- | --

**Comment by Lyken17** [comment]
Are you using the latest THOP? Try `pip install --upgrade thop` and calculate again.

**Comment by Lyken17** [comment]
whoops. That's a mistake I made. I was using 1024 ** 3 as the definition of million, but actually it should be 1000 ** 3. The readme has been updated. Please have a check.
