### ISSUE TITLE
AttributeError: 'torch.Size' object has no attribute 'numel'

### ISSUE THREAD

**Issue by SuckChen** [Lyken17/pytorch-OpCounter#45]
Traceback (most recent call last):
  File "/home/gpu/chen/IMIXNet-PyTorch/code/get_Netpara.py", line 21, in <module>
    print("Torch:",  thop.profile(torch.nn.Conv2d(1, 128, (3, 3)), inputs=(torch.zeros((1, 1, 128, 128)),), verbose=False)[0])
  File "/home/gpu/.conda/envs/pytorch4/lib/python3.6/site-packages/thop/profile.py", line 92, in profile
    model(*inputs)
  File "/home/gpu/.conda/envs/pytorch4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    hook_result = hook(self, input, result)
  File "/home/gpu/.conda/envs/pytorch4/lib/python3.6/site-packages/thop/count_hooks.py", line 20, in count_convNd
    kernel_ops = m.weight.size()[2:].numel()  # Kw x Kh
AttributeError: 'torch.Size' object has no attribute 'numel'

what‘s the problem here ?
the version of thop is wrong?

**Comment by Lyken17** [comment]
Upgrade your PyTorch and thop to lastest version.

**Comment by sureJ0824** [comment]
can you tell me which version for pytorch  you use , and I use pytorch 0.4.0 and upgrade the thop, but meet the same problem. thank you  a lot

**Comment by Lyken17** [comment]
PyTorch version should be newer than 1.0

**Comment by mrfarazi** [comment]
@sureJ0824, if you want to use pytorch 0.4.0 (which I needed to do as I was calculating flops for a legacy project), you can use dummy variable to get its number of elements. 

For example, in `count_hooks.py` you can make the following change:
`# kernel_ops = m.weight.size()[2:].numel()  # Kw x Kh
kernel_ops = torch.zeros(m.weight.size()[2:]).numel() # Kw x Kh`

This essentially creates a same sized tensor of zeros, which then can be passed to numel(). This worked for me in pytorch=0.4.0
