### ISSUE TITLE
calculation of AvgPooling

### ISSUE THREAD

**Issue by fortunex3000** [Lyken17/pytorch-OpCounter#55]
Could you please give a closer explanation for the calculation of the AvgPool FLOPs? Despite I know that the impact of pooling layers is minimal, I'd like to understand the calculation. As I get from the code the formular for 2dAvgPooling you use is:  _(kernel_size + 1) * H_out * W_out * in_channels * out_channels_
But if I consider the formular on the pytorch website I'd calculate them as follows:
For each kernel beeing applied on your input you have _kernel_size * kernel_size - 1_ additions plus one division plus one multiplication of your _kernel_size_ inside the denominator. You apply _out_channels_ kernels on _in_channels_ input channels which result in a _H_out * W_out_ output. This is the computation for all multiplications and additions. To be compliant with the regular understanding of MACs and FLOPs you devide by 2 as two MACs result in one FLOP. So finally I get the formular: _FLOPs = (kernel_size * kernel_size - 1) * H_out * W_out * in_channels * out_channels / 2_

**Comment by Lyken17** [comment]
I think you suggestion is correct. In total there are **H_out * W_out  * out_channels** pixels and each pixel takes ** in_channels * (kernel_size * kernel_size - 1) ** operations. 

For MACs and FLOPs, it is not simple 2 times calculation. In short, it depends how you count the multiplication for floating numbers. I will refactor the codebase to fix the issue.

**Comment by fortunex3000** [comment]
Thank you! Will you please let me know as soon as you fixed the code, so that I can update the python package?

**Comment by Lyken17** [comment]
After talking to an expert in hardware, I made a clarification of [MACs and FLOPs](https://github.com/Lyken17/pytorch-OpCounter/tree/master/benchmark). For AVGPooling, the updated MAC should be **H_out * W_out * out_channels**.  If you agree with it, I will update the corresponding code recently.

**Comment by Lyken17** [comment]
@fortunex3000 any comments?

**Comment by llbin-oppo** [comment]
> After talking to an expert in hardware, I made a clarification of [MACs and FLOPs](https://github.com/Lyken17/pytorch-OpCounter/tree/master/benchmark). For AVGPooling, the updated MAC should be **H_out * W_out * out_channels**. If you agree with it, I will update the corresponding code recently.

But if you do this, it is different from the statistical method of TensorFlow and the user’s conventional perception
