### ISSUE TITLE
'torch.Size' object has no attribute 'numel'

### ISSUE THREAD

**Issue by liuboss1992** [Lyken17/pytorch-OpCounter#59]
Hi Lyken, thank you for your powerful tool, however, I met some difficult with it and get error as 
```
'torch.Size' object has no attribute 'numel'
```

My environment is python 3.6 with torch 0.4.1.

**Comment by Lyken17** [comment]
https://github.com/Lyken17/pytorch-OpCounter/issues/45

> PyTorch version should be newer than 1.0
