### ISSUE TITLE
GFLOPS

### ISSUE THREAD

**Issue by InstantWindy** [Lyken17/pytorch-OpCounter#6]
Hi!When my convolution kernel value is only 1 and -1 or when my input value is only 1 and -1, will the GFLOPS of the convolution operation be small? Thanks!

**Comment by InstantWindy** [comment]
In fact, convolution kernel values of 1 and -1 or input values of 1 and -1 do not make the network run fast, right? Thanks!

**Comment by Lyken17** [comment]
It depends on the underlying implementation. In some library, it might run faster.
