### ISSUE TITLE
Formula/method of flop calculation

### ISSUE THREAD

**Issue by Rakshith2597** [Lyken17/pytorch-OpCounter#62]
Thanks for the open-source work. Is there a document/blog which explains how flops are actually calculated for each layers/operations? Like for bn layer,etc

**Comment by Lyken17** [comment]
Currently no. I am planning to add some new features and do not have the bandwidth to write a doc. 

If you are interested in the details, you can refer to https://github.com/Lyken17/pytorch-OpCounter/blob/master/thop/count_hooks.py.
