### ISSUE TITLE
Missing hook functions for inherited layer

### ISSUE THREAD

**Issue by tuxzz** [Lyken17/pytorch-OpCounter#63]
## Problem
I have a layer inherited from Conv2d:
````python
class KaimingInitConv2d(torch.nn.Conv2d):
  def reset_parameters(self):
    torch.nn.init.kaiming_normal_(self.weight.data, a=0.0, nonlinearity="leaky_relu")
    if self.bias is not None:
      self.bias.data.fill_(0.0)
````
In `thop`, the `add_hooks` function can't found the inheritance relationship between `KaimingInitConv2d` and `torch.nn.Conv2d`, it missing the MACs in every `KaimingInitConv2d` layer object.

## Possible solution
Replace dict getitem
````python
def add_hooks(m):
    ...
    if m_type in custom_ops:  # if defined both op maps, use custom_ops to overwrite.
        fn = custom_ops[m_type]
    elif m_type in register_hooks:
        fn = register_hooks[m_type]
    ...
````
With dict iteration:
````python
def add_hooks(m):
    ...
    for op_type, op_fn in register_hooks.items():
        if isinstance(m, op_type):
            fn = op_fn
            break
    for op_type, op_fn in custom_ops.items(): # if defined both op maps, use custom_ops to overwrite.
        if isinstance(m, op_type):
            fn = op_fn
            break
    ...
````

I will send a PR as soon as available.

**Comment by tuxzz** [comment]
Sent PR #64

**Comment by Lyken17** [comment]
No, op_counting shouldn't inherit from parent classes. Consider the following example

```python
class NewConv2(nn.Conv2d):
    def forward(self, x):
        x1 = F.conv2d(x)
        x2 = F.conv2d(x1)
        return x2 
```

The computation function is no longer the same as parent's, so the FLOPs.

**Comment by Lyken17** [comment]
In your case, the kaiming init should be applied outside objects, rather than define a new class.

**Comment by tuxzz** [comment]
Okay, I will add inherited class into `custom_ops` dict.
For convenience I have to apply kaiming init in a new defined class.
