### ISSUE TITLE
Does it work for LSTM layer?

### ISSUE THREAD

**Issue by zhipeng-fan** [Lyken17/pytorch-OpCounter#67]

**Comment by Lyken17** [comment]
Currently, no. The support is on the way (slowly). It would be great if you can scratch a PR to help.

**Comment by ericlearning** [comment]
What kind of layers does it work? Will it work for Custom LSTM implementations?

**Comment by Lyken17** [comment]
Plan to support LSTM. For customized layer, you need to define your counting rule.

**Comment by Lyken17** [comment]
@vBaiCai has submitted a PR to support #78 . You are welcome to have a try.
