### ISSUE TITLE
The ops is slightly different from the original ones in the paper of ShuffleNet.

### ISSUE THREAD

**Issue by ChiSuWq** [Lyken17/pytorch-OpCounter#72]
Hello.

I used thop to calculate the flops of ShuffleNet which is 137M (g=3) in the original paper while 147.554M in thop. And the ops of shufflenet_v2_x1.5 is 310M in your profile but 291M in original paper.

What results in the difference?
And What is the output on earth? Flops or MAC? I believe it's more like Flops. But as shown in your profile, you call it MAC. Now I am confused deeply.

Could you explain it for me? 
Thank your time in advance.

**Comment by ChiSuWq** [comment]
I check the code about 'clever_format' which use 'num / 1e3' for the unit conversion.
I change it to 'num / 1024'.

Then I get better ops-140.719M on shufflenetv1 which is  very close to the original one 140M shown in the ShuffleNetv2 paper.

Is it better using 1024 for unit conversion?

**Comment by Lyken17** [comment]
> ops of shufflenet_v2_x1.5 is 310M in your profile but 291M

Do you mean parameters?

> the flops of ShuffleNet which is 137M (g=3) in the original paper while 147.554M in thop

I think the main difference is caused by BN. Most frameworks do not take BN into consideration.

> Flops or MAC? I believe it's more like Flops

MACs by default, for the difference, you can refer to  https://github.com/Lyken17/pytorch-OpCounter/tree/master/benchmark. 

> Is it better using 1024 for unit conversion?

No. 1M = 10^6
