### ISSUE TITLE
why wrong

### ISSUE THREAD

**Issue by Prines** [Lyken17/pytorch-OpCounter#73]
from thop import profile
input = torch.rand(1,3,224,224)
model1 = models.resnet18()
flops, params = profile(model1, inputs=(input,))

**Comment by Prines** [comment]
TypeError: new() received an invalid combination of arguments - got (list, dtype=torch.dtype), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the keywords were incorrect: dtype
 * (object data, torch.device device)
      didn't match because some of the keywords were incorrect: dtype

**Comment by agrichron** [comment]
I also have met this error.  when i remove the `dtype=torch.float64`, the code rigthly run.

**Comment by Lyken17** [comment]
This should be fixed now. Can you try `pip install thop --upgrade`? @agrichron @Prines
