### ISSUE TITLE
Calculation of parameters is inaccurate when modules do not participate in the forward

### ISSUE THREAD

**Issue by colorjam** [Lyken17/pytorch-OpCounter#75]
Hi, I found that the calculation of parameters is inaccurate if the modules are defined while not participating in the forward.

**Comment by Lyken17** [comment]
Current strategy is: if a module is not defined in calculate_ops, both params and flops are treated as zero by default. Do you suggest to count the parameters instead of treating it as zero?

**Comment by colorjam** [comment]
No. I suggest that if a module not in the forward pass, its parameters should not be counted. 
For example:
```
class Model(nn.Module):
    def __init__(self):
        super(Model,self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 3)
        self.conv2 = nn.Conv2d(6, 6, 3)
        self.conv3 = nn.Conv2d(6, 6, 3)

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)

        return x 
```
the model flops and params are 27912.0 and 828.0.
If I comment `x=self.conv3(x)`, the flops become 22632.0 but the params remain unchanged.

I notice that params are counted by 
```
for p in m.parameters():
            m.total_params += torch.DoubleTensor([p.numel()])
```

move params counter into `basic_hook.py` and consistent with flops counter would be better.

**Comment by Lyken17** [comment]
Question here, if a module is not used in forward, why should we care its params and flops?

**Comment by colorjam** [comment]
Yes, the current implementation does not calculate a module flops if it's not used in forward. While params are calculated. You can check the example above. If `conv3` not used in the forward, FLOPs are not calculated but Params are.

**Comment by noranartv** [comment]
@Lyken17  I think @colorjam meant would it possible for thop to only count the functions that is called in forward(). I face the same problem where sometimes init() contains so many things, but I only use a few things in forward().

So to @Lyken17 question, "if a module is not used in forward, why should we care its params and flops?". You are right that we shouldn't care about those modules that are not in forward, but sounds like thop implementation today count everything in init().

**Comment by Lyken17** [comment]
I see. Let me updated the code.

**Comment by Lyken17** [comment]
Fixed 

```python
class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.linear1 = nn.Linear(100, 100)
        self.linear2 = nn.Linear(100, 100)

    def forward(self, x):
        x = self.linear1(x)
        x = self.linear2(x)
        return x

m = MyModule()

macs, params = profile(
    m, inputs=(torch.rand(1, 100),),
        verbose=True
)

print(f"{macs} MACs    {params} parameters")
'''20000.0 MACs    20200.0 parameters'''
```

```python
class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.linear1 = nn.Linear(100, 100)
        self.linear2 = nn.Linear(100, 100)

    def forward(self, x):
        x = self.linear1(x)
        return x

m = MyModule()

macs, params = profile(
    m, inputs=(torch.rand(1, 100),),
        verbose=True
)

print(f"{macs} MACs    {params} parameters")
'''10000.0 MACs    10100.0 parameters'''
```

**Comment by noranartv** [comment]
thank you so much
