### ISSUE TITLE
flops in Conv2D is wrong

### ISSUE THREAD

**Issue by luuuyi** [Lyken17/pytorch-OpCounter#8]
First, nice work. But I found something wrong when calculating flops in torch.nn.Conv2d, in count_hooks.py file, the `out_w = y.size(2) // m.stride[0]` is wrong, it must be `out_w = y.size(2)`. The same as `out_h`.
So the flops result is less than standard ones.

**Comment by luuuyi** [comment]
And y.size(2) should be H in N*C*H*W, in your code, it's W.

**Comment by Lyken17** [comment]
Thanks for the correction. PR merged.
