### ISSUE TITLE
How to calculate 3D CNN Flops

### ISSUE THREAD

**Issue by slighting666** [Lyken17/pytorch-OpCounter#83]
How to calculate 3D CNN flops ？
thanks

**Comment by jucyLL** [comment]
Have you solved it？

**Comment by Lyken17** [comment]
Got some time recently and plan to update the features

What kind of 3D operation you are using?

**Comment by Lyken17** [comment]
Feel free to re-open this issue if you still have the demand to compute 3d cnn.
