### ISSUE TITLE
Example of 3rd party module rule

### ISSUE THREAD

**Issue by ElectronicGuy** [Lyken17/pytorch-OpCounter#86]
Hi. Thanks for your work!! I was wondering how to definea 3rd party model rule. In particular, my model has a forward function as follows:
```
def forward (self, x):
    x = self.input_cell(x)
    x = self.middle_cell(x)
    x = self.last_cell(x)
    return x
```
where each cell is internally composed by standard convolutinal layers, BN and ReLus. I don't quite understand what to write in count_yout_model method. Do you have any suggestions? 

```
class YourModule(nn.Module):
    # your definition
def count_your_model(model, x, y):
    # your rule here
    

input = torch.randn(1, 3, 224, 224)
macs, params = profile(model, inputs=(input, ), 
                        custom_ops={YourModule: count_your_model})
```
Also,  can you explain the functionality of x and y inputs to such method?

**Comment by ElectronicGuy** [comment]
Looking at closed issues, I realized that I only received warnings. Therefore, no need to define a 3rd party rule. I close this issue.

**Comment by jucyLL** [comment]
Have you solved it？
