### ISSUE TITLE
MACs in sparse models.

### ISSUE THREAD

**Issue by ElectronicGuy** [Lyken17/pytorch-OpCounter#87]
Hi, thanks for sharing your work! 
I used your op_counter to evaluate the number of MACs on a very sparse CNN model (92% sparsity) and on the baseline dense model (0% sparsity). The op_counter returns the same number of MACs, even if several convolutional filters are completely zeroed.

Do you have any suggestion on how to support operation counting for sparse models?
Let me know if you need furher details.

**Comment by Lyken17** [comment]
THOP does not consider sparisity as the sparse calculation actually highly depends on the low-level implementation (e.g., how zeros are skipped). 

If you want to calculate for sparse modules, you may want to define your own counting rules so it can fit your user case.
