### ISSUE TITLE
[WARN] Cannot find rule of module 

### ISSUE THREAD

**Issue by peylnog** [Lyken17/pytorch-OpCounter#89]
Hello,thanks for your excellent job . But，there is a warning i don‘t understand.
what is the rule of module ? Can you give an example how to use it in individual module. 

WARN:
[WARN] Cannot find rule for <class 'net.model.DC_blocks'>. Treat it as zero Macs and zero Params.
ps(DC_blocks is my model )

**Comment by Lyken17** [comment]
This means there is no count rule for `net.model.DC_blocks` as it is defined by 3rd party / yourself. By default, the FLOPs of such modules is the summation of all child modules.

**Comment by Mhaiyang** [comment]
Hi, I encounter the same problem. Does it mean that the final FLOPs include my defined module? Is it OK to just ignore the warning?

**Comment by Lyken17** [comment]
@Mhaiyang Yes, it is safe (in most cases) to ignore the warning. I will improve the log to make users more comfortable : )

**Comment by Mhaiyang** [comment]
@Lyken17 Thanks!

**Comment by flyingmrwang** [comment]
@Lyken17 

> This means there is no count rule for `net.model.DC_blocks` as it is defined by 3rd party / yourself. By default, the FLOPs of such modules is the summation of all child modules.

Sorry, but I am still confused about this warning. As you suggested, it is ok that the module is not recognizable. And the default rule to calculate is to take sum for all the child modules. But is there any risk to cause wrong calculation?
